### PR TITLE
Rework "shared" design of NKCommon

### PR DESCRIPTION
**Pull request by claucambra**
Having an `NKCommon` instance always accessible in a singleton design is very convenient when only dealing with one account at a time. 

Unfortunately, when dealing with a situation where several accounts need to be active at the same time, the singleton pattern becomes a problem. On the desktop file provider extension we have domains set up for each account and, since the file provider extension is one process, the shared `NKCommon` instance limits how many accounts we can have set up in `NextcloudKit`.

This can be fixed by making `NKCommon`, which holds the user account data, not be a singleton but instead an instance member of `NextcloudKit`: 

- For the iOS client `NKCommon.shared` can largely be replaced by `NextcloudKit.shared.nkCommonInstance`
- In the desktop file provider extension, we can just create new instances of `NextcloudKit` per domain, each of which employs its own instance of `NKCommon`

### CODE REVIEW

**Comment by marinofaggiana** [comment]
@claucambra first of all I have changed the base into develop because PR -> develop - > main new version.

**Comment by marinofaggiana** [comment]
@claucambra there do not exists the new class:

 https://github.com/nextcloud/NextcloudKit/blob/main/NextcloudKit/NKShareAccounts.swift

can I modify your code ?

**Review by marinofaggiana — CHANGES_REQUESTED** [review]
NKShareAccounts do not exists

**Comment by claucambra** [comment]
> NKShareAccounts do not exists

This is based on an old revision of develop, rebasing

**Comment by claucambra** [comment]
@marinofaggiana rebased now

**Review by marinofaggiana — APPROVED** [review]

**Comment by marinofaggiana** [comment]
@claucambra seems works good, I approved and will make more test,. for now you can use it (develop) 

cc @Ivansss @SystemKeeper it's good for you ?

**Comment by Ivansss** [comment]
Yeah, this change doesn't affect the Talk iOS app.
Thanks for the ping 😉

**Pull request merged**
